name: Deploy to AWS (Dev)

on:
  push:
    branches:
      - develop

env:
  NG_BUILD_WORKDIR: argo-heli/
  NG_BUILD_OUTPUT_DIR: argo-heli/dist/argo-heli/browser/
  AWS_REGION: eu-central-2
  AWS_BUCKET_NAME_DEV: argo-heli-ch-static-website-bucket-dev

jobs:
  build-angular-app:
    name: Angular Build
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ${{ env.NG_BUILD_WORKDIR }}

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup Node.js $
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ${{ env.NG_BUILD_WORKDIR }}package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.NG_BUILD_OUTPUT_DIR }}
          if-no-files-found: error

  copy-to-s3-dev:
    name: Deploy to S3 (Dev)
    runs-on: ubuntu-22.04
    environment: dev
    needs:
      - build-angular-app
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: ./build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOYMENT_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOYMENT_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3 (Dev)
        run: aws s3 sync ./build/artifact s3://${{ env.AWS_BUCKET_NAME_DEV }} --delete
